language: python
python:
- 3.6
services:
- docker
install:
- pip install --no-cache-dir pyyaml
- mkdir -p bin
- export PATH=$PWD/bin:$PATH
- curl -ssL https://storage.googleapis.com/kubernetes-helm/helm-v2.6.1-linux-amd64.tar.gz
  | tar -xz -C bin --strip-components 1 linux-amd64/helm
- chmod +x bin/helm
- helm init --client-only
script:
- |
  if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login -u ${DOCKER_USERNAME} -p "${DOCKER_PASSWORD}"
    export PUSH="--push"
  fi
- "./build.py build --commit-range ${TRAVIS_COMMIT_RANGE} $PUSH"
branches:
  only:
  - master
  - v0.4.x
before_install:
env:
  global:
  - secure: BWGK+VDD/a2sv+6aJ+36PMa8nUDhgGuzKLRocbaMYXJnOnKw3ptfkcAdg4K5kJ584GLL7eboMHIstnSivSVhivip+Kbl6LgCawCA+QPs/XZDXLwDdD0u+upBYyjxvKllwHEtRzYBK6FfyVZl6IsiXDEGwxzaBrOxbfhtUcSci6r+T79ZfqiOzWyt3zYvpR9DyzNo6mj39sYzvLH1ZT070NtnWW6j9ZTQV00xZlZO6C5eGNA0p4xm18xslEzz8zMtXS/vHcphVb27Wn/OHLuxLhLRLF9Y4EMi7zJa0FsRrYbaMExRJ3mNswdbdXeV0sag41nxQzsAejrPoL0GWpPCXgsyJAiZa4w6Fh6prI8CgWGdrm2D3ktkofyzKXUgrdVBlw3/b1ILykzKmNxcY2xacxeiwdApK1JeNYIrTD37p5A4RPmjRP4nU7t6sBpRQGVoXv5EHTMMoE1M7EBZMPbREMYmiRAjXxPnYg1D8jMpDFaIYMH7sTPMWfj0lGAT3we7skxoDS+UY95288Q2Ckm58DIeEFK0I92Ibi+eMLWHZ0R6h2PxAbW9i6ud/kmtUDwmbcLzCc2uxTPs1YJ+i5MDxPgBaRtYQKfOK5Nnd33r+7mNSN9R4NI3OYrSImhB7PQdZB9rtFNWHZodIW+Yyz6zev9M4SZ/ey8cQFYOMRf9Wkw=
  - secure: cE6z5toK1k9eUBBiEME9uyvZ050G9QiHmcOXEY5zxUPY/PQGvqVYBdBcdT0rbHPiSW4U6msSoiLziGojGMEqN1WUSQrYuUuE518RCGRQeOcYGmBHcJ9WU+ud7BRw89KvCbi5/H81QcsyV2KIawPghj0xhHXDPnhCxNEOximwswO/mYjrdIKX1oT4M1kRwF6uFCIezcd0qFVsMpJFN2/PJlngjjbs9sLqonCIso8hy4Tp56plzoVQuiQWZFfeKpIBud7I4beEj8VvqHeBI+OrLWmeLygmtLaycxZx/rMDx+s6kJNINbR5pLz+WBwkPjH6YJ777L+wsFEKY2/Chc8ZQPh6Q6PrF6Phqo7uYfCpBHi58XtfX2sPcGRb3Rt2iyZT65/++3rO0PG37wNoS3Yw6hcffm0+mRqYd0+Hr+iKPmTCKB09WgHz14LJYxM0GBuJ7tEUTQQA7TIY6YQZlhB0yjVaMhD04jbiSDoKned1FBRHmjfMoFMXka+p5t65RcbwLsRhHHHyXiMsyWy9D1UDwU6vW7AZY8c9brRA9CtqbT4IG7RTBx8wM8Qgw5jZpcswbzj6wdPGHLEL05mMT6UWt460Ji4jNdTr1C3PtaozezyfqoL2KBDL/OyQeC86pWWZfZ4WgUH2n1JjADJL9C3AlmH0ofb+FqKyI4zWxZ6SELs=
