language: python
python:
- 3.6
services:
- docker
install:
- pip install --no-cache-dir pyyaml
- mkdir -p bin
- export PATH=$PWD/bin:$PATH
- curl -ssL https://storage.googleapis.com/kubernetes-helm/helm-v2.6.1-linux-amd64.tar.gz | tar -xz -C bin --strip-components 1 linux-amd64/helm
- chmod +x bin/helm
- helm init --client-only
script:
- |
  if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login -u ${DOCKER_USERNAME} -p "${DOCKER_PASSWORD}"
    export PUSH="--push"
  fi
- "./build.py build --commit-range ${TRAVIS_COMMIT_RANGE} $PUSH"
branches:
  only:
  - master
  - v0.4.x
before_install:

env:
  global:
  - secure: aPUAJm5JCyIBQFirKHG482e9UrEkqKBR2UFbJKBao2VOL7aPVZmAjZK9/JDwZf5322UQeKtxPfoan9E013BBd0/waUmLu5GzbbigEGonjA9XG4ce2VHBi1F123DJyAQy+Nb5wLlpu+jL1LZzhBjvD0qBvzKSqFUYSQo8TrB8zkMZbjbpeV9FVEf4U9wyJZJ7c5c9bQhtvn8m+wscZeK7rXxLtz1pRuax95oQRvrWcm03WFusLU1HGw/OtGyHnqKqFSrmI+DnUteEVqfPpL2wmyvNE6gFTyKWPZoupHVJ53/IOOLiRYZDgt7nV525JI/0uSAjdjn+naK9rbLwtuGSrkg1Wj0QA0yV2MftW4tJi4i8fDtXXwP8wBFSkQtBhcPFSccvTiMnjnjCT9DMttUDadI8XSyjXOKblTNwn59ygrvNVMENDCc5FtxuCXaG547zqDW4NRTu8zZs8h3eKJinX+4sZ/99mbI23M8chFY7Ot5DftD5z/nUtHLA6dKQ2Qp1lONGtL2HRQ+iEFFt7uzj7vsciSyqpV4jSSTJ5hG0+UElf9cjEqHO0we0VJtx5M2ZQM8ysbY9zPGMJO0qrhsM5byQ/HQWiyw+9FVwjpFdCAnU/jjbmaV1ZTAeSSODEDlIx8v79wTTZ0Z5H5G4r9PqDy4AMUxBUedzvWttClw+G40=
  - secure: aGGcxcxa7uUbjbjPiv2VuevLPJM1L6WP3iENc7UxIB/dT55BsUPxfJehjgos1efDbEhKYeILeiiJbyBOljdOUTKTIGUUZxkx0bn3a99afBDl5DRPHNulmITABQozdL4hqvvsIx0jbKZKk6dm1jbQTYuK7NaQ6tX1vGu5b6L4/xQg/+49M7ugkoslKRTk+CPRSv7NqOPqREu8YPUz8OLFP3WfiCfJZAZJHBpaD7x8lOFC54bydSGSveyLZFS1Hf0jWZs3Ai8DR5kZLxBO0XkpYaW4XFo93WBc1VIHS85qA/Mwe//JaVhvQQ9eF9363r1hsvd+wUL3wFYu5IpQbSK6+RaaESJrPfUNIYAjOyx0Mjjhr3qdypQvCykddeFZBbEc9/mqrJWp9rO9rpTyl4hdAqlvYEBVWBfvelYkNtrTYynLYF65oVbo1WbJlMmfeLCmonQJdiZMb4VBDUcAf2s3mXEMCTBhnTOuEu6LWE6HWKpoMixWWTFxBtg/2mv2BUfe03pe7Qd+JMo3kjTkVJsv4qznQRR5/QT4mxZW3WaOUIEyvT9eApD4VbewpjgSXz5MX0a/QX9Wm7KdtY+ntONXnx/g8Ce6aDm4j/0/efHpzrttseMVc2HwlwSgGN0r92UqoeEw+Xy2M6bjQKoo6wkQJFQPJzC19Wm5/ydzkzOKz+0=
